version: '3.8'

services:
  fastapi-app:
    build: .
    container_name: aiops-llm
    ports:
      - "8001:8001"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - CASE_MGT_URL=http://casemgt-api/api/v1/case/
      - OPENSHIFT_API_SERVER=https://<openshift api url>:6443
      - OPENSHIFT_TOKEN=<token>
      - ACTION_REQ=N
      - LLM_INFERENCE_QUEUE=llm_inference_queue

    networks:
      - anomaly-network
networks:
  anomaly-network:
    external: true

