version: "3.9"
services:

  otel-aggregator:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-aggregator
    command: [ "--config", "/etc/otel-config.yaml" ]
    ports:
    - "4318:4318" 
    - "4317:4317"
    volumes:
    - ./etc/otel-config.yaml:/etc/otel-config.yaml:Z
networks:
  default:
    external:
      name: otel-net