apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openclaw

resources:
  - 01-otel-collector-config.yaml
  - 02-otel-collector.yaml
  - 03-prometheus-config.yaml
  - 04-prometheus.yaml
