receivers:
  hostmetrics:
    root_path: /host # <— important on Podman/macOS
    collection_interval: 5s
    scrapers:
      cpu: {} # no keys here
      memory: {}
      filesystem: {}
      disk: {}
      load: {}
      network: {}

processors:
  resource:
    attributes:
    - key: host
      value: "Edge-GreatJey-macbook-pro"
      # value: "${HOSTNAME}"
      action: upsert
  attributes:
    actions:
    - action: insert
      key: host
      from_attribute: host

  batch: {}

exporters:
  prometheus:
    endpoint: "0.0.0.0:9464"
    resource_to_telemetry_conversion:
      enabled: true

  otlphttp/metrics:
    endpoint: http://otel-aggregator:4318
    tls:
      insecure: true
  # otlp:
  #   endpoint: "<aggregator-endpoint-url>:<port>"
  #   tls:
  #     insecure: true

  debug:
    verbosity: detailed # See full telemetry data structure

service:
  pipelines:
    metrics:
      receivers: [ hostmetrics ]
      processors: [ resource, batch ]
      exporters: [ prometheus, debug, otlphttp/metrics ]
