#!/usr/bin/env bash
# Phase 2 helper — OpenShell + OpenClaw + private LLM (greenfield).
#
# Usage:
#   ./scripts/phase2-openshell.sh plan          # printable checklist
#   ./scripts/phase2-openshell.sh write-env     # ~/labs/openshell-env.sh from pins
#   ./scripts/phase2-openshell.sh deploy          # automated steps 2–6 (Agent Sandbox → OpenClaw)
#   ./scripts/phase2-openshell.sh check         # pass/fail gates (run after each major step)
#   ./scripts/phase2-openshell.sh harden      # kit patches (after OpenClaw deploy)
#   ./scripts/phase2-openshell.sh providers [profile]  # LLM preset hints (litemaas|vllm|maas-16k|openai)
#   ./scripts/phase2-openshell.sh probe           # full in-pod LLM model probe
#   ./scripts/phase2-openshell.sh ui              # Control UI URL + gateway token
#
# Env: DEMO_KIT_ROOT, OPENCLAW_NS, OPENSHELL_NS, PROBE_*, SKIP_PHASE2_PROBE
set -euo pipefail

GF_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export GF_ROOT
[[ -f "$GF_ROOT/config/env.local" ]] && source "$GF_ROOT/config/env.local"
# shellcheck source=scripts/resolve-demo-kit.sh
source "$GF_ROOT/scripts/resolve-demo-kit.sh"

resolve_kit() {
  resolve_demo_kit
  # shellcheck source=/dev/null
  source "$DEMO_KIT_ROOT/scripts/supply-chain-pins.env"
}

resolve_kit

KUBECTL="$(command -v oc || command -v kubectl)"
OPENCLAW_NS="${OPENCLAW_NS:-openclaw}"
OPENSHELL_NS="${OPENSHELL_NS:-openshell}"
LAB_DIR="${OPENCLAW_LAB_DIR:-$HOME/labs/openshell-on-openshift-lab}"
ENV_FILE="${OPENSHELL_ENV_FILE:-$HOME/labs/openshell-env.sh}"

c_green=$'\033[1;32m'; c_red=$'\033[1;31m'; c_yellow=$'\033[1;33m'; c_blue=$'\033[1;34m'; c_reset=$'\033[0m'
ok()   { printf '  %s✓%s %s\n' "$c_green" "$c_reset" "$*"; }
fail() { printf '  %s✗%s %s\n' "$c_red" "$c_reset" "$*"; }
warn() { printf '  %s!%s %s\n' "$c_yellow" "$c_reset" "$*"; }
step() { printf '\n%s==>%s %s\n' "$c_blue" "$c_reset" "$*"; }

helm_version_ok() {
  command -v helm >/dev/null 2>&1 && helm version --short 2>/dev/null | grep -qE 'v3\.'
}

cmd_plan() {
  cat <<EOF
Phase 2 — OpenShell + OpenClaw (~45–90 min, mostly manual)

Full guide: $GF_ROOT/docs/PHASE-2-OPENSHELL.md
Demo kit:   $DEMO_KIT_ROOT/README.md (Phase 3)

Steps:
  1. Pins + lab checkout     $DEMO_KIT_ROOT/scripts/clone-openshell-lab.sh
  2. Bastion env file        ./scripts/phase2-openshell.sh write-env && source $ENV_FILE
  2b. Helm 3 (if needed)    ./scripts/install-helm3.sh install
  3–6. Automated deploy      ./scripts/phase2-openshell.sh deploy
  7. Kit hardening           ./scripts/phase2-openshell.sh harden
  8. Verify                  ./scripts/phase2-openshell.sh check
                             ./scripts/phase2-openshell.sh probe

Or run the full phase via:  ./scripts/greenfield-install.sh openshell

After each manual sub-step (if not using deploy), run:  ./scripts/phase2-openshell.sh check
EOF
}

cmd_write_env() {
  step "Writing $ENV_FILE"
  mkdir -p "$(dirname "$ENV_FILE")"
  cat >"$ENV_FILE" <<EOF
# Generated by phase2-openshell.sh — source before OpenShell/OpenClaw work
export OPENCLAW_NAMESPACE=${OPENCLAW_NS}
export OPENSHELL_NAMESPACE=${OPENSHELL_NS}
export OPENSHELL_VERSION=${OPENSHELL_CHART_VERSION}
export AGENT_SANDBOX_RELEASE=${AGENT_SANDBOX_RELEASE}
export AGENT_SANDBOX_MANIFEST="https://github.com/kubernetes-sigs/agent-sandbox/releases/download/\${AGENT_SANDBOX_RELEASE}/manifest.yaml"
export OPENCLAW_LAB_DIR="${LAB_DIR}"
export PATH="${HOME}/.local/bin:\${PATH}"
EOF
  ok "Wrote $ENV_FILE"
  printf '\n  source %s\n' "$ENV_FILE"
}

gate() {
  local label="$1"
  shift
  if "$@" >/dev/null 2>&1; then
    ok "$label"
    return 0
  fi
  fail "$label"
  return 1
}

openclaw_pod() {
  "$KUBECTL" -n "$OPENCLAW_NS" get pod -l app.kubernetes.io/name=openclaw \
    --field-selector=status.phase=Running \
    -o jsonpath='{.items[0].metadata.name}' 2>/dev/null
}

cmd_probe() {
  local pod out rc
  PROBE_PROVIDER="${PROBE_PROVIDER:-openai}"
  PROBE_MAX_TOKENS="${PROBE_MAX_TOKENS:-16}"
  PROBE_TIMEOUT="${PROBE_TIMEOUT:-60000}"

  pod="$(openclaw_pod)"
  if [[ -z "$pod" ]]; then
    fail "No Running openclaw pod in namespace ${OPENCLAW_NS}"
    exit 1
  fi

  step "In-pod LLM probe — ${pod} (${OPENCLAW_NS})"
  printf '  provider=%s max_tokens=%s timeout_ms=%s\n' \
    "$PROBE_PROVIDER" "$PROBE_MAX_TOKENS" "$PROBE_TIMEOUT"

  printf '\n--- config validate ---\n'
  "$KUBECTL" -n "$OPENCLAW_NS" exec "$pod" -- sh -lc \
    'set -eu; node /app/openclaw.mjs config validate'

  printf '\n--- openshell gateway ---\n'
  "$KUBECTL" -n "$OPENCLAW_NS" exec "$pod" -- sh -lc \
    'set -eu; openshell status --gateway-endpoint "${OPENSHELL_GATEWAY_URL}"'

  printf '\n--- model probe ---\n'
  set +e
  out="$("$KUBECTL" -n "$OPENCLAW_NS" exec "$pod" -- sh -lc \
    "set -eu
node /app/openclaw.mjs models status --probe \
  --probe-provider ${PROBE_PROVIDER} \
  --probe-max-tokens ${PROBE_MAX_TOKENS} \
  --probe-timeout ${PROBE_TIMEOUT} \
  --json")"
  rc=$?
  set -e
  printf '%s\n' "$out"

  if [[ "$rc" -ne 0 ]]; then
    fail "Model probe command exited ${rc}"
    exit 1
  fi

  if command -v jq >/dev/null 2>&1; then
    if echo "$out" | jq -e '
      (.probe.status // .status // "") == "ok"
      or ([.. | objects | select(has("status")) | .status] | index("ok"))
    ' >/dev/null 2>&1; then
      ok "Model probe status: ok"
      return 0
    fi
  elif echo "$out" | grep -qE '"status"[[:space:]]*:[[:space:]]*"ok"'; then
    ok "Model probe status: ok"
    return 0
  fi

  fail "Model probe did not report ok — check baseUrl, my-llm-key, network policy, contextWindow"
  exit 1
}

cmd_check() {
  local fails=0
  step "Phase 2 readiness — $($KUBECTL whoami 2>/dev/null || echo 'not logged in')"

  if ! helm_version_ok; then
    fail "Helm 3 missing — run: $GF_ROOT/scripts/install-helm3.sh install"
    fails=$((fails + 1))
  else
    ok "Helm 3 installed"
  fi
  gate "Lab checkout @ pin" "$DEMO_KIT_ROOT/scripts/clone-openshell-lab.sh" status || fails=$((fails + 1))
  gate "Agent Sandbox controller" "$KUBECTL" -n agent-sandbox-system get deploy/agent-sandbox-controller || fails=$((fails + 1))
  gate "OpenShell StatefulSet" "$KUBECTL" -n "$OPENSHELL_NS" get statefulset/openshell || fails=$((fails + 1))
  gate "OpenClaw Deployment" "$KUBECTL" -n "$OPENCLAW_NS" get deploy/openclaw || fails=$((fails + 1))
  gate "Secret my-llm-key" "$KUBECTL" -n "$OPENCLAW_NS" get secret/my-llm-key || fails=$((fails + 1))
  gate "Secret openclaw-gateway-token" "$KUBECTL" -n "$OPENCLAW_NS" get secret/openclaw-gateway-token || fails=$((fails + 1))
  gate "OpenClaw Route" "$KUBECTL" -n "$OPENCLAW_NS" get route/openclaw || fails=$((fails + 1))

  if [[ -f "${LAB_DIR}/manifests/openclaw/config.yaml" ]]; then
    if grep -q 'api.openai.com' "${LAB_DIR}/manifests/openclaw/config.yaml" 2>/dev/null \
      && ! grep -qE 'litemaas|maas-|vllm|\.svc' "${LAB_DIR}/manifests/openclaw/config.yaml" 2>/dev/null; then
      warn "config.yaml may still point at public OpenAI — confirm baseUrl + network policy"
    else
      ok "config.yaml edited (non-default LLM host)"
    fi
  else
    fail "lab config.yaml missing at ${LAB_DIR}/manifests/openclaw/config.yaml"
    fails=$((fails + 1))
  fi

  if POD="$("$KUBECTL" -n "$OPENCLAW_NS" get pod -l app.kubernetes.io/name=openclaw \
    --field-selector=status.phase=Running -o jsonpath='{.items[0].metadata.name}' 2>/dev/null)" \
    && [[ -n "$POD" ]]; then
    if "$KUBECTL" -n "$OPENCLAW_NS" exec "$POD" -- sh -lc \
      'node /app/openclaw.mjs config validate' >/dev/null 2>&1; then
      ok "OpenClaw config validate (in-pod)"
    else
      fail "OpenClaw config validate (in-pod)"
      fails=$((fails + 1))
    fi
  else
    warn "OpenClaw pod not Running — skip in-pod validate"
  fi

  printf '\n'
  if [[ "$fails" -gt 0 ]]; then
    warn "$fails check(s) failed — see $GF_ROOT/docs/PHASE-2-OPENSHELL.md#troubleshooting"
    return 1
  fi
  ok "Phase 2 checks passed"
  printf '  LLM probe: ./scripts/phase2-openshell.sh probe\n'
  printf '  Control UI: %s/scripts/netobserv-e2e-openclaw-test.sh ui-hints\n' "$DEMO_KIT_ROOT"
}

cmd_harden() {
  step "Kit hardening (post OpenClaw deploy)"
  export LAB_CFG="${LAB_CFG:-$LAB_DIR/manifests/openclaw/config.yaml}"
  export LAB_ROOT="$LAB_DIR"
  export OPENCLAW_NS
  "$DEMO_KIT_ROOT/scripts/patch-openclaw-seed-idempotent.sh"
  "$DEMO_KIT_ROOT/scripts/ensure-openclaw-ui-origin.sh"
  ok "Hardening applied — Control UI: ./scripts/phase2-openshell.sh ui"
}

deploy_agent_sandbox() {
  step "Agent Sandbox controller (${AGENT_SANDBOX_RELEASE})"
  "$KUBECTL" apply -f "${AGENT_SANDBOX_MANIFEST}"
  "$KUBECTL" -n agent-sandbox-system rollout status \
    deployment/agent-sandbox-controller --timeout=300s
  ok "Agent Sandbox ready"
}

deploy_openshell_prereqs() {
  step "OpenShell namespace + SCC + JWT signing secret"
  "$KUBECTL" create namespace "${OPENSHELL_NAMESPACE}" \
    --dry-run=client -o yaml | "$KUBECTL" apply -f -
  if command -v oc >/dev/null 2>&1; then
    oc adm policy add-scc-to-user privileged \
      -z openshell-sandbox -n "${OPENSHELL_NAMESPACE}" >/dev/null 2>&1 \
      || warn "SCC grant may already exist"
  else
    warn "oc not found — ensure openshell-sandbox SA has privileged SCC"
  fi
  if ! "$KUBECTL" -n "${OPENSHELL_NAMESPACE}" get secret openshell-jwt-keys >/dev/null 2>&1; then
    local key_dir
    key_dir="$(mktemp -d)"
    openssl genpkey -algorithm Ed25519 -out "${key_dir}/signing.pem"
    openssl pkey -in "${key_dir}/signing.pem" -pubout -out "${key_dir}/public.pem"
    printf 'openshell-0\n' >"${key_dir}/kid"
    "$KUBECTL" -n "${OPENSHELL_NAMESPACE}" create secret generic openshell-jwt-keys \
      --from-file=signing.pem="${key_dir}/signing.pem" \
      --from-file=public.pem="${key_dir}/public.pem" \
      --from-file=kid="${key_dir}/kid" \
      --dry-run=client -o yaml | "$KUBECTL" apply -f -
    rm -rf "${key_dir}"
    ok "Created openshell-jwt-keys"
  else
    ok "openshell-jwt-keys already present"
  fi
}

deploy_openshell_helm() {
  step "OpenShell Helm chart (${OPENSHELL_VERSION})"
  helm upgrade --install openshell \
    oci://ghcr.io/nvidia/openshell/helm-chart \
    --version "${OPENSHELL_VERSION}" \
    --namespace "${OPENSHELL_NAMESPACE}" \
    --values "${LAB_DIR}/manifests/openshell/values.yaml"
  "$KUBECTL" -n "${OPENSHELL_NAMESPACE}" rollout status \
    statefulset/openshell --timeout=600s
  ok "OpenShell StatefulSet ready"
}

patch_openclaw_pullable_image() {
  # Lab pins June digest @sha256:a91dbc… (removed from Quay). Mirror to QUAY_ORG first.
  local default_image="${OPENCLAW_IMAGE:-${OPENCLAW_GATEWAY_IMAGE}}"
  local gateway_image="${OPENCLAW_GATEWAY_IMAGE:-$default_image}"
  local sandbox_image="${OPENCLAW_SANDBOX_IMAGE:-$default_image}"
  local old_digest="${OPENCLAW_STALE_DIGEST:-sha256:a91dbc1cc1879a46137da1b73e5c270ea3094cdc3753f5ce8636168c9e1d8d0c}"
  local old_image="quay.io/ryan_nix/openclaw-openshift@${old_digest}"

  step "OpenClaw image (gateway + sandbox): ${gateway_image}"

  if command -v podman >/dev/null 2>&1; then
    if ! podman manifest inspect "${gateway_image}" >/dev/null 2>&1; then
      warn "Cannot pull ${gateway_image} on bastion"
      warn "  On reference bastion: ./scripts/mirror-openclaw-image-to-quay.sh"
      warn "  Then export OPENCLAW_GATEWAY_IMAGE / OPENCLAW_SANDBOX_IMAGE in config/env.local"
    fi
  fi

  if [[ -f "${LAB_DIR}/manifests/openclaw/deployment.yaml" ]]; then
    sed -i.bak \
      -e "s|${old_image}|${gateway_image}|g" \
      -e "s|quay.io/ryan_nix/openclaw-openshift:2026\\.08\\.04|${gateway_image}|g" \
      -e "s|quay.io/ryan_nix/openclaw-openshift:openclaw-v2026\\.7\\.1-2|${gateway_image}|g" \
      -e "s|quay.io/ryan_nix/openclaw-openshift:hummingbird-openclaw-v2026\\.7\\.1-2|${gateway_image}|g" \
      -e "s|quay.io/ryan_nix/openclaw-openshift:latest|${gateway_image}|g" \
      "${LAB_DIR}/manifests/openclaw/deployment.yaml"
    ok "Patched deployment.yaml (gateway/init)"
  fi

  if [[ -f "${LAB_DIR}/manifests/openclaw/config.yaml" ]]; then
    sed -i.bak \
      -e "s|${old_image}|${sandbox_image}|g" \
      -e "s|quay.io/ryan_nix/openclaw-openshift:2026\\.08\\.04|${sandbox_image}|g" \
      -e "s|quay.io/ryan_nix/openclaw-openshift:openclaw-v2026\\.7\\.1-2|${sandbox_image}|g" \
      -e "s|quay.io/ryan_nix/openclaw-openshift:hummingbird-openclaw-v2026\\.7\\.1-2|${sandbox_image}|g" \
      -e "s|quay.io/ryan_nix/openclaw-openshift:latest|${sandbox_image}|g" \
      "${LAB_DIR}/manifests/openclaw/config.yaml"
    ok "Patched config.yaml (sandbox agent image)"
  fi

  if [[ -f "${LAB_DIR}/manifests/openshell/values.yaml" ]] \
    && grep -qE "$old_digest|openclaw-openshift@" "${LAB_DIR}/manifests/openshell/values.yaml" 2>/dev/null; then
    sed -i.bak \
      -e "s|${old_image}|${sandbox_image}|g" \
      -e "s|quay.io/ryan_nix/openclaw-openshift:2026\\.08\\.04|${sandbox_image}|g" \
      -e "s|quay.io/ryan_nix/openclaw-openshift:hummingbird-openclaw-v2026\\.7\\.1-2|${sandbox_image}|g" \
      "${LAB_DIR}/manifests/openshell/values.yaml"
    ok "Patched openshell values.yaml"
  fi

  if "$KUBECTL" get cm openshell-config -n "${OPENSHELL_NAMESPACE}" >/dev/null 2>&1; then
    "$KUBECTL" get cm openshell-config -n "${OPENSHELL_NAMESPACE}" -o yaml \
      | sed -e "s|${old_image}|${sandbox_image}|g" \
        -e "s|quay.io/ryan_nix/openclaw-openshift:2026\\.08\\.04|${sandbox_image}|g" \
        -e "s|quay.io/ryan_nix/openclaw-openshift:hummingbird-openclaw-v2026\\.7\\.1-2|${sandbox_image}|g" \
      | "$KUBECTL" apply -f - >/dev/null 2>&1 || true
  fi
}

deploy_openclaw() {
  local url gateway_url
  gateway_url="http://openshell.${OPENSHELL_NAMESPACE}.svc.cluster.local:8080"

  step "OpenClaw namespace + LLM secret + lab config"
  "$KUBECTL" create namespace "${OPENCLAW_NAMESPACE}" \
    --dry-run=client -o yaml | "$KUBECTL" apply -f -
  patch_openclaw_pullable_image
  export LAB_CFG="${LAB_CFG:-$LAB_DIR/manifests/openclaw/config.yaml}"
  export OPENCLAW_NS="${OPENCLAW_NAMESPACE}"
  "$DEMO_KIT_ROOT/scripts/patch-openclaw-seed-idempotent.sh" || warn "seed harden patch skipped"
  # shellcheck source=scripts/site-config.sh
  source "$GF_ROOT/scripts/site-config.sh"
  site_config_ensure openshell
  site_config_apply openshell

  step "OpenClaw gateway token + manifests"
  if ! "$KUBECTL" -n "${OPENCLAW_NAMESPACE}" get secret openclaw-gateway-token >/dev/null 2>&1; then
    openssl rand -hex 32 | "$KUBECTL" -n "${OPENCLAW_NAMESPACE}" \
      create secret generic openclaw-gateway-token \
      --from-file=token=/dev/stdin \
      --dry-run=client -o yaml | "$KUBECTL" apply -f -
    ok "Created openclaw-gateway-token"
  else
    ok "openclaw-gateway-token already present"
  fi

  kubectl_kustomize_apply() {
    kubectl kustomize "${LAB_DIR}/manifests/openclaw" | \
      sed "s/openshell\.openshell\.svc/openshell.${OPENSHELL_NAMESPACE}.svc/" | \
      "$KUBECTL" -n "${OPENCLAW_NAMESPACE}" apply -f -
  }
  if command -v kubectl >/dev/null 2>&1; then
    kubectl_kustomize_apply
  else
    oc kustomize "${LAB_DIR}/manifests/openclaw" | \
      sed "s/openshell\.openshell\.svc/openshell.${OPENSHELL_NAMESPACE}.svc/" | \
      "$KUBECTL" -n "${OPENCLAW_NAMESPACE}" apply -f -
  fi

  "$KUBECTL" -n "${OPENCLAW_NAMESPACE}" set env deployment/openclaw \
    "OPENSHELL_GATEWAY_URL=${gateway_url}" >/dev/null 2>&1 || true
  "$KUBECTL" -n "${OPENCLAW_NAMESPACE}" rollout restart deployment/openclaw
  "$KUBECTL" -n "${OPENCLAW_NAMESPACE}" rollout status deployment/openclaw --timeout=900s

  url="$("$KUBECTL" -n "${OPENCLAW_NAMESPACE}" get route openclaw \
    -o jsonpath='https://{.spec.host}' 2>/dev/null || true)"
  if [[ -n "$url" ]]; then
    "$KUBECTL" -n "${OPENCLAW_NAMESPACE}" set env deployment/openclaw \
      "OPENCLAW_PUBLIC_URL=${url}" >/dev/null 2>&1 || true
    "$KUBECTL" -n "${OPENCLAW_NAMESPACE}" rollout status deployment/openclaw --timeout=900s
  fi
  ok "OpenClaw deployed (route: ${url:-pending})"
}

cmd_deploy() {
  step "Phase 2 automated deploy"
  cmd_write_env
  # shellcheck source=/dev/null
  source "$ENV_FILE"
  export OPENCLAW_NAMESPACE="${OPENCLAW_NAMESPACE:-$OPENCLAW_NS}"
  export OPENSHELL_NAMESPACE="${OPENSHELL_NAMESPACE:-$OPENSHELL_NS}"
  export PATH="${HOME}/.local/bin:${PATH}"

  step "Verify OpenClaw image pullable (fail fast)"
  OPENCLAW_GATEWAY_IMAGE="${OPENCLAW_GATEWAY_IMAGE:-${OPENCLAW_IMAGE:-}}"
  OPENCLAW_SANDBOX_IMAGE="${OPENCLAW_SANDBOX_IMAGE:-${OPENCLAW_GATEWAY_IMAGE:-}}"
  "$DEMO_KIT_ROOT/scripts/verify-image-pulls.sh" --phase2

  helm_version_ok || "$GF_ROOT/scripts/install-helm3.sh" install
  [[ -d "$LAB_DIR/manifests/openclaw" ]] \
    || "$DEMO_KIT_ROOT/scripts/clone-openshell-lab.sh"

  deploy_agent_sandbox
  deploy_openshell_prereqs
  deploy_openshell_helm
  deploy_openclaw

  ok "Deploy steps complete — run: ./scripts/phase2-openshell.sh check"
}

cmd_providers() {
  local profile="${1:-}"
  local doc="$GF_ROOT/docs/PHASE-2-LLM-PROVIDERS.md"
  case "$profile" in
    ""|list|help|-h|--help)
      cat <<EOF
LLM provider presets — full doc: $doc

  litemaas   RHOAI LiteMaaS 128k (Qwen3.6-35B-A3B)
  vllm       Generic self-hosted vLLM / OpenAI-compatible
  maas-16k   Legacy workshop MaaS (16k, thinking off)
  openai     Public api.openai.com (stock lab policy)

Usage: $0 providers <profile>
EOF
      ;;
    litemaas|lite-maas|rhoai)
      cat <<'EOF'
Profile: litemaas (128k)
  LLM_BASE_URL=https://litemaas.example.com/v1
  LLM_MODEL=Qwen3.6-35B-A3B
  primary=openai/Qwen3.6-35B-A3B
  contextWindow=131072  maxTokens=12288  enable_thinking=true
  policy host: litemaas.example.com:443

Edit: ~/labs/openshell-on-openshift-lab/manifests/openclaw/config.yaml
      ~/labs/openshell-on-openshift-lab/manifests/openclaw/policies/managed-policy.yaml
EOF
      printf '\n  Full JSON + apply steps: %s\n' "$doc#litemaas-recommended"
      ;;
    vllm|generic)
      cat <<'EOF'
Profile: vllm (generic)
  export LLM_BASE_URL="https://YOUR-HOST/v1"
  export LLM_MODEL="your-model-id"
  primary=openai/<LLM_MODEL>
  Set contextWindow/maxTokens to match your server limits
  policy host: YOUR-HOST:443 (managed-policy.yaml)

Verify from bastion + in-cluster before deploy (see PHASE-2-OPENSHELL.md step 4a).
EOF
      printf '\n  Full template: %s\n' "$doc#vllm-generic-openai-compatible"
      ;;
    maas-16k|maas|workshop)
      cat <<'EOF'
Profile: maas-16k (legacy workshop)
  LLM_BASE_URL=https://maas-rhdp.apps.maas.redhatworkshops.io/v1  # example
  LLM_MODEL=qwen3-14b
  primary=openai/qwen3-14b
  contextWindow=16384  maxTokens=6144  enable_thinking=false

Short demos only — investigate turns may hit stopReason=length.
EOF
      printf '\n  Details: %s\n' "$doc#maas-16k-legacy-workshop"
      ;;
    openai|public)
      cat <<'EOF'
Profile: openai (public API)
  Stock lab config.yaml — create my-llm-key with OpenAI API key.
  No managed-policy change (api.openai.com already allowed).
  Not recommended for customer demos (egress, cost).
EOF
      ;;
    *)
      echo "unknown profile: $profile (try: litemaas, vllm, maas-16k, openai)" >&2
      exit 1
      ;;
  esac
}

cmd_ui() {
  step "OpenClaw Control UI"
  local url token
  url="$("$KUBECTL" -n "$OPENCLAW_NS" get route openclaw -o jsonpath='https://{.spec.host}' 2>/dev/null || true)"
  token="$("$KUBECTL" -n "$OPENCLAW_NS" get secret openclaw-gateway-token \
    -o jsonpath='{.data.token}' 2>/dev/null | base64 -d 2>/dev/null || true)"
  [[ -n "$url" ]] && printf '  URL:   %s\n' "$url" || fail "Route openclaw not found"
  [[ -n "$token" ]] && printf '  Token: %s\n' "$token" || fail "Secret openclaw-gateway-token not found"
  printf '\n  Warm-up: open URL → paste token → /new → send first message (sandbox spawns 15–60s)\n'
}

case "${1:-plan}" in
  plan|help|-h|--help) cmd_plan ;;
  write-env|env) cmd_write_env ;;
  deploy|install) cmd_deploy ;;
  check|verify) cmd_check ;;
  probe|model-probe) cmd_probe ;;
  providers|provider) cmd_providers "${2:-}" ;;
  harden) cmd_harden ;;
  ui|url) cmd_ui ;;
  *)
    echo "usage: $0 {plan|write-env|deploy|check|probe|providers|harden|ui}" >&2
    exit 1
    ;;
esac
