version: "3.9"
services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    # network_mode: "host"
    volumes:
    - ./etc/otel-config.yaml:/etc/otel-config.yaml:Z
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - /:/host:ro # mount the entire host FS so /proc etc. are visible for mac
    command: [ "--config", "/etc/otel-config.yaml" ]
    ports:
    - "9464:9464" # Prometheus exporter
   
  prometheus:
    image: prom/prometheus:latest
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
    - "9090:9090"
    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
    - "3000:3000" # Grafana UI
    environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=admin
    - GF_DASHBOARDS_JSON_ENABLED=true
    - GF_DASHBOARDS_JSON_PATH=/var/lib/grafana/dashboards
    volumes:
    - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    - ./grafana/grafana-data:/var/lib/grafana # persist Grafana DB and config

    depends_on:
    - prometheus
networks:
  default:
    external:
      name: otel-net