receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317" # Ensure this port is open
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:
    timeout: 10s
exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug ] # persistance exporter needs to added to store edge metrics to S3 storage
